//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIDEOTEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empresa
    {
        public int emp_id_empresa { get; set; }
        public string emp_nombre { get; set; }
        public string emp_telefono { get; set; }
        public string emp_direccion { get; set; }
        public string emp_correo { get; set; }
        public string emp_logo { get; set; }
    }
}
